### ISSUE TITLE
request failed 429 code + shortcuts dont work

### ISSUE THREAD

**Issue by flowen** [Arrendy/gpt3-vscode-extension#16]
<img width="400" alt="CleanShot 2022-12-13 at 12 27 00@2x" src="https://user-images.githubusercontent.com/4084169/207317838-fa24e5bf-d815-4867-b75f-7a09413ee319.png">

also, shortcuts don't work they give me these: ©≈

**Comment by MikeBirdTech** [comment]
429s are typically for [too many requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429). Make sure to not button mash, OpenAI's API can take a few seconds to return. 

There is a status bar item that should tell you if the extension is generating anything.

To check if there are conflicting key bindings, go to `preferences` => `keyboard shortcuts` and in the new tab listing all the key bindings, type in `alt +` and the letter for the shortcut. If more than one result is returned, you'll need to change or remove all but one.

**Comment by flowen** [comment]
thanks @Arrendy 
I had just installed and not used either the web version or anything else. So a bit surprised, but perhaps its just that GPT getting hammered in general. 

the characters is the keyboard setting, but I see now that the shortcuts haven't been set in the first place. I can simply bind them, sorry should've looked myself first, but it perhaps means that the plugin isn't binding them correctly(?).

**Comment by flowen** [comment]
[also just found my solution](https://stackoverflow.com/questions/60870113/mac-generating-%E2%88%86%CB%9A%C2%AC-characters-instead-of-executing-vscode-shortcuts-that-involve)
