### ISSUE TITLE
Update keybindings

### ISSUE THREAD

**Issue by pxlvoid** [Arrendy/gpt3-vscode-extension#18]
Can you make keybindings for Mac users?

**Comment by MikeBirdTech** [comment]
Sure thing. I don't have a Mac, do you mind sharing 4 easy keybindings that aren't assigned by default?

**Comment by dalechyn** [comment]
@Arrendy 
Can the shortcuts be in a preferences section?
I am using Mac and not able to use this extension at all.

**Comment by MikeBirdTech** [comment]
@h0tw4t3r 
All keybindings can be set in `preferences` > `keyboard shortcuts`.

All commands can also be called through the command palette .

If you provide me with 4 short keyboard shortcuts that aren't being used on a mac, I can update the default

**Comment by semanticentity** [comment]
Ask GPT: 

ctrl + '

Create code from docs:

ctrl + \

Create documentation:

ctrl + ]

GPT code review: 

ctrl + [


<img width="1094" alt="Screen Shot 2023-01-14 at 2 51 27 AM" src="https://user-images.githubusercontent.com/109195117/212462109-6622d33d-6547-496a-8eb8-eb52a49e69bd.png">

**Comment by MikeBirdTech** [comment]
Thamls @semanticentity!

I've added those keybindings
