### ISSUE TITLE
Limited Return Output

### ISSUE THREAD

**Issue by gabecano** [Arrendy/gpt3-vscode-extension#22]
I selected 20+ lines of code in a python program to be reviewed.  The returned output was in a popup window and seemed to be truncated.   I copied the contents of the returned output and verified this was the case.

Used version v0.11.1 of GPT-3 A.I. Coding Assistant.
My Setup
Version: 1.74.2 (user setup)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by MikeBirdTech** [comment]
Is your value for `GPT.maxTokens` high enough to support prompts that long?

**Comment by gabecano** [comment]
I tested increasing the token to the 2048 max supported and the returned output seems correct now.  Thank you for the suggestion.
