### ISSUE TITLE
error 401 no idea why is trowing me that error

### ISSUE THREAD

**Issue by Teru-dot-png** [Arrendy/gpt3-vscode-extension#7]
![image](https://user-images.githubusercontent.com/68662335/206879592-05ea8212-3115-45e4-b54d-c8f30b322a4c.png)

did everything as instructed wich is only one instruction

**Comment by MikeBirdTech** [comment]
Make sure to set your credentials in settings.json

**Comment by MikeBirdTech** [comment]
@Teru-dot-png Did you resolve the issue? Or do you need any more assistance?

**Comment by MiguelB512** [comment]
Hello, I entered the wrong API key and now i am unsure how to reset it.

**Comment by MikeBirdTech** [comment]
Open up command palete and run `Update OpenAI API Key`
There will be a prompt to enter your correct API Key.
Reload the window, and it should be good to go!

**Comment by MiguelB512** [comment]
Thank you so much, that worked
