### ISSUE TITLE
Can't figure out where to put my API key

### ISSUE THREAD

**Issue by Mifulapirus** [Arrendy/gpt3-vscode-extension#8]
I'm sure I'm missing something and I'm not very familiar with Extensions in general, so I can't figure out where _settings.json_ is or where to put my API key.

**Comment by MikeBirdTech** [comment]
The next release (later today) will have the configuration page appear in settings to make it easier. In the meantime, please open `settings.json` and add entries for:

```
    "GPT.openaiOrg": "org-<id>",
    "GPT.openaiApiKey": "<API Key>",
    "GPT.model": "text-davinci-003",
    "GPT.maxTokens": 250,
    "GPT.temperature": 0.3,
```
    
 The new release will also remove the organization header, for now
